version: '3.7'
services:
  #################
  ### Front-end ###
  #################

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
    volumes:
      - client:/app
      - /app/.next
      - /app/node_modules

  ################
  ### Back-end ###
  ################

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    volumes:
      - server:/app
      - /app/dist
      - /app/node_modules

  ######################
  ### Infrastructure ###
  ######################

  caddy:
    build:
      context: ./caddy/dns/local
      dockerfile: Dockerfile
    volumes:
      - etc-caddy:/etc/caddy

volumes:
  # Mutagen volumes
  client:
  etc-caddy:
  server:

x-mutagen:
  sync:
    client:
      alpha: './packages/client'
      beta: 'volume://client'
      mode: 'two-way-resolved'
      ignore:
        paths:
          - '.next'
          - 'node_modules'

    etc-caddy:
      alpha: './caddy/dns/local'
      beta: 'volume://etc-caddy'

    server:
      alpha: './packages/server'
      beta: 'volume://server'
      mode: 'two-way-resolved'
      ignore:
        paths:
          - 'dist'
          - 'node_modules'
