version: '3.7'
services:
  #################
  ### Front-end ###
  #################

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/client:/app
      - /app/.next
      - /app/node_modules
    env_file:
      - ./apps/client/.env

  ################
  ### Back-end ###
  ################

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/server:/app
      - /app/dist
      - /app/node_modules
    env_file:
      - ./apps/server/.env

  ######################
  ### Infrastructure ###
  ######################

  caddy:
    volumes:
      - ./apps/caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
