version: '3.8'
services:
  #################
  ### Front-end ###
  #################

  client:
    container_name: client
    platform: linux/amd64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
    env_file:
      - ./.env
    build:
      args:
        - BASE_PATH=${BASE_PATH}
        - PORT=${PORT}
        - TUS_URL=${TUS_URL}
        - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
        - SENTRY_ENABLED=${SENTRY_ENABLED}
        - SENTRY_DSN=${SENTRY_DSN}

  ################
  ### Back-end ###
  ################

  server:
    container_name: server
    platform: linux/amd64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
      - db
      - backend
    volumes:
      - ./data/tmp:/tmp/uploads
      - ./data/uploads:/uploads
    env_file:
      - ./.env

  ################
  ### Database ###
  ################

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - db
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  ######################
  ### Infrastructure ###
  ######################

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
    depends_on:
      - nextjs
    restart: always

  caddy:
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./caddy/srv:/srv
      - ./data/caddy:/data/caddy
      - ./plugins:/plugins
      - ./data/uploads:/uploads
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - backend
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

  tus:
    container_name: tus
    image: tusproject/tusd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
    command: -behind-proxy -upload-dir /tmp/uploads -base-path /tus/files/
    volumes:
      - ./data/tmp:/tmp/uploads

networks:
  caddy:
  db:
  backend:

volumes:
  caddy_config:
  caddy_data:
