version: '3.8'

services:
  #################
  ### Front-end ###
  #################

  client:
    build:
      context: .
      dockerfile: ./packages/client/docker/Dockerfile.prod

  ################
  ### Back-end ###
  ################

  server:
    build:
      context: .
      dockerfile: ./packages/server/docker/Dockerfile.prod
