version: '3.8'

services:
  #################
  ### Front-end ###
  #################

  ui:
    build:
      context: .
      dockerfile: ./apps/ui/docker/Dockerfile.dev
    volumes:
      - ./apps/ui:/app
      - /app/.next
      - /app/node_modules

  ################
  ### Back-end ###
  ################

  api:
    build:
      context: .
      dockerfile: ./apps/api/docker/Dockerfile.dev
    volumes:
      - ./apps/api:/app
      - /app/dist
      - /app/node_modules
