version: '3.7'
services:
  #################
  ### Front-end ###
  #################

  client:
    container_name: client
    platform: linux/amd64
    networks:
      - caddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    build:
      context: ./apps/client
      dockerfile: ./Dockerfile
    volumes:
      - ./apps/client:/app
      - /app/.next
      - /app/node_modules
    env_file:
      - ./apps/client/.env

  ################
  ### Back-end ###
  ################

  server:
    container_name: server
    platform: linux/amd64
    networks:
      - caddy
      - postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    build:
      context: ./apps/server
      dockerfile: ./Dockerfile
    volumes:
      - ./apps/server:/app
      - /app/dist
      - /app/node_modules
    env_file:
      - ./apps/server/.env

  ################
  ### Database ###
  ################

  postgres:
    container_name: postgres
    networks:
      - postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    networks:
      - postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    links:
      - postgres:postgres

  ######################
  ### Infrastructure ###
  ######################

  caddy:
    container_name: caddy
    networks:
      - caddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    image: caddy:2-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./apps/caddy:/srv
      - ./apps/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data/caddy
      - caddy_config:/config
      - caddy_data:/data
    env_file:
      - .env
    stdin_open: true
    tty: true

networks:
  caddy:
  postgres:

volumes:
  caddy_config:
  caddy_data:
