version: '3.8'

services:
  #################
  ### Front-end ###
  #################

  client:
    build:
      context: .
      dockerfile: ./packages/client/docker/Dockerfile.dev
    volumes:
      - ./packages/client:/app
      - /app/.next
      - /app/node_modules

  ################
  ### Back-end ###
  ################

  server:
    build:
      context: .
      dockerfile: ./packages/server/docker/Dockerfile.dev
    volumes:
      - ./packages/server:/app
      - /app/dist
      - /app/node_modules
