version: '3.7'
services:
  #################
  ### Front-end ###
  #################

  client:
    container_name: client
    platform: linux/amd64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
    env_file:
      - ./.env

  ################
  ### Back-end ###
  ################

  server:
    container_name: server
    platform: linux/amd64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
      - db
      - backend
    volumes:
      - ./data/tmp:/tmp
      - ./data/uploads:/uploads
    env_file:
      - ./.env

  ################
  ### Database ###
  ################

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - db
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql
    env_file:
      - ./.env

  ######################
  ### Infrastructure ###
  ######################

  caddy:
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./data/caddy:/data/caddy
      - ./data/plugins:/plugins
      - ./data/uploads:/uploads
      - ./caddy/srv:/srv
      - caddy_config:/config
      - caddy_data:/data
    env_file:
      - ./.env
    # stdin_open: true
    # tty: true

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - backend
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

  tus:
    container_name: tus
    image: tusproject/tusd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - caddy
    command: -behind-proxy -upload-dir /tmp/uploads -base-path /tus/files/
    volumes:
      - ./data/tmp:/tmp

networks:
  caddy:
  db:
  backend:

volumes:
  caddy_config:
  caddy_data:
