version: '3.8'
services:
  #################
  ### Front-end ###
  #################

  client:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/client:/app
      - /app/.next
      - /app/node_modules

  ################
  ### Back-end ###
  ################

  server:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/server:/app
      - /app/dist
      - /app/node_modules
