version: '3.8'

services:
  #################
  ### Front-end ###
  #################

  ui:
    container_name: ui
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
    build:
      context: .
      dockerfile: ./apps/ui/docker/Dockerfile.dev
      args:
        - HOST=${HOST}
        - NODE_ENV=${NODE_ENV}
        - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
    volumes:
      - ./apps/ui:/app
      - /app/.next
      - /app/node_modules
    env_file:
      - ./.env

  ################
  ### Back-end ###
  ################

  api:
    container_name: api
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
      - api_network
    build:
      context: .
      dockerfile: ./apps/api/docker/Dockerfile.dev
    volumes:
      - ./apps/api:/app
      - /app/dist
      - /app/node_modules
      - ./data/tmp:/tmp/uploads
      - ./data/uploads:/uploads
    env_file:
      - ./.env

  ################
  ### Database ###
  ################

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - api_network
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  ######################
  ### Infrastructure ###
  ######################

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
    command: nginx -g 'daemon off;'
    volumes:
      - ./data/uploads:/uploads
      - ./nginx:/etc/nginx/templates
    ports:
      - '80:80'
    env_file:
      - ./.env

  tusd-local:
    container_name: tusd
    image: tusproject/tusd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
    command: -behind-proxy -base-path=/tus/files -upload-dir=/tmp/uploads
    volumes:
      - ./data/tmp:/tmp/uploads

  tusd-s3:
    container_name: tusd
    image: tusproject/tusd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
    command: -behind-proxy -base-path=/tus/files -s3-bucket=${AWS_S3_BUCKET} -s3-endpoint=${AWS_S3_ENDPOINT} -s3-object-prefix=tmp/
    env_file:
      - ./.env

networks:
  api_network:
  nginx_network:
