version: '3.7'
services:
  #################
  ### Front-end ###
  #################

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile.prod

  ################
  ### Back-end ###
  ################

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile.prod

  ######################
  ### Infrastructure ###
  ######################

  caddy:
    build:
      context: ./packages/caddy/dns/${CADDY_DNS_METHOD}
      dockerfile: Dockerfile
    volumes:
      - ./packages/caddy/dns/${CADDY_DNS_METHOD}/Caddyfile:/etc/caddy/Caddyfile:ro
