version: '3.8'
services:
  #################
  ### Front-end ###
  #################

  client:
    container_name: client
    platform: linux/amd64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
    env_file:
      - ./.env
    build:
      args:
        - TUS_URL=${TUS_URL}
        - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
        - SENTRY_ENABLED=${SENTRY_ENABLED}
        - SENTRY_DSN=${SENTRY_DSN}

  ################
  ### Back-end ###
  ################

  server:
    container_name: server
    platform: linux/amd64
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
      - server_network
    volumes:
      - ./data/tmp:/tmp/uploads
      - ./data/uploads:/uploads
    env_file:
      - ./.env

  ################
  ### Database ###
  ################

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - server_network
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  ######################
  ### Infrastructure ###
  ######################

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
    volumes:
      - ./data/plugins:/plugins
      - ./data/uploads:/uploads
      - ./nginx:/etc/nginx/templates
    ports:
      - '80:80'
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - server_network
    command: redis-server --requirepass ${REDIS_PASSWORD}

  tus:
    container_name: tus
    image: tusproject/tusd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nginx_network
    command: -behind-proxy -upload-dir=/tmp/uploads -base-path=${TUS_SUFFIX}
    volumes:
      - ./data/tmp:/tmp/uploads

networks:
  server_network:
  nginx_network:
