version: '3.8'

services:
  #################
  ### Front-end ###
  #################

  ui:
    build:
      context: .
      dockerfile: ./apps/ui/docker/Dockerfile.prod

  ################
  ### Back-end ###
  ################

  api:
    build:
      context: .
      dockerfile: ./apps/api/docker/Dockerfile.prod
