version: '3.8'
services:
  #################
  ### Front-end ###
  #################

  client:
    build:
      dockerfile: Dockerfile.prod

  ################
  ### Back-end ###
  ################

  server:
    build:
      dockerfile: Dockerfile.prod
