replicaCount: 1

image:
  repository: registry.digitalocean.com/tarrasque/client
  pullPolicy: Always
  tag: production

imagePullSecrets:
  - name: registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hosts:
    - host: cloud.tarrasque.app
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-secret-client
      hosts:
        - cloud.tarrasque.app

env:
  - name: VERSION
    value: "1.0.0"
  - name: HOST
    value: "https://cloud.tarrasque.app"
  - name: NODE_ENV
    value: "production"
  - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
    value: "5m"
  - name: SENTRY_ENABLED
    value: "true"
  - name: SENTRY_DSN
    value: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
