name: '[SANDBOX] Deploy'

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy-client:
    uses: ./.github/workflows/deploy-client-sandbox.yaml
    secrets: inherit

  deploy-server:
    uses: ./.github/workflows/deploy-server-sandbox.yaml
    secrets: inherit

  deploy-tusd:
    uses: ./.github/workflows/deploy-tusd-sandbox.yaml
    secrets: inherit
