name: Deploy cert-manager

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-cert-manager.yaml'
      - 'helm/cert-manager/**'

env:
  CHART: cert-manager
  DEPLOYMENT: cert-manager
  NAMESPACE: cert-manager

jobs:
  deploy-cert-manager:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 tarrasqueapp-cluster

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm dependency build helm/${{ env.CHART }}
          helm upgrade --install ${{ env.CHART }} ./helm/${{ env.CHART }} --namespace ${{ env.NAMESPACE }} --create-namespace

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT }} --namespace ${{ env.NAMESPACE }}
