name: Deploy client

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-client.yaml'
      - 'helm/client/**'
      - 'packages/client/**'

env:
  CHART: client
  DEPLOYMENT: client
  NAMESPACE: client
  DIRECTORY: ./packages/client
  REGISTRY: registry.digitalocean.com/tarrasqueapp
  IMAGE_TAG: staging

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container image
        working-directory: ${{ env.DIRECTORY }}
        run: docker build -t ${{ env.REGISTRY }}/${{ env.CHART }}:${{ env.IMAGE_TAG }} -f Dockerfile.prod .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.CHART }}:${{ env.IMAGE_TAG }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 tarrasqueapp-cluster

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          helm upgrade --install ${{ env.CHART }} ./helm/${{ env.CHART }} --namespace ${{ env.NAMESPACE }} --create-namespace

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT }} --namespace ${{ env.NAMESPACE }}
