name: Deploy ingress-nginx

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-ingress-nginx.yaml'
      - 'helm/ingress-nginx/**'

env:
  CHART: ingress-nginx
  DEPLOYMENT: ingress-nginx-controller
  NAMESPACE: ingress-nginx

jobs:
  deploy-ingress-nginx:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 tarrasqueapp

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm dependency build helm/${{ env.CHART }}
          helm upgrade --install ${{ env.CHART }} ./helm/${{ env.CHART }} --namespace ${{ env.NAMESPACE }} --create-namespace

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT }} --namespace ${{ env.NAMESPACE }}
